[package]
name = "brk_vecs"
description = "A simple index/value store"
keywords = ["vec", "disk", "data"]
categories = ["database"]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
brk_vecs_macros = { workspace = true }
ctrlc = { version = "3.4.7", features = ["termination"] }
libc = "0.2.174"
log = { workspace = true }
memmap2 = "0.9.7"
parking_lot = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
pco = "0.4.6"
