[package]
name = "brk_vecs"
description = "A storeable vec"
keywords = ["vec", "disk", "data"]
categories = ["database"]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
brk_core = { workspace = true }
brk_exit = { workspace = true }
libc = "0.2.174"
log = { workspace = true }
memmap2 = "0.9.7"
parking_lot = {workspace = true}
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
zstd = "0.13.3"
