[package]
name = "brk_vecs"
description = "Traits for Vecs structs throughout BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
serde = { workspace = true }
vecdb = { workspace = true }
