[package]
name = "brk_structs"
description = "Structs used throughout BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
allocative = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
brk_error = { workspace = true }
byteview = { workspace = true }
derive_deref = { workspace = true }
itoa = "1.0.15"
jiff = { workspace = true }
num_enum = "0.7.4"
rapidhash = "4.1.0"
ryu = "1.0.20"
schemars = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
strum = { version = "0.27", features = ["derive"] }
vecdb = { workspace = true }
zerocopy = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
