[package]
name = "brk_structs"
description = "Structs used throughout BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
allocative = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
brk_error = {workspace = true}
vecdb = {workspace = true}
byteview = { workspace = true }
derive_deref = { workspace = true }
jiff = { workspace = true }
rapidhash = "4.1.0"
serde = { workspace = true }
serde_bytes = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
