[package]
name = "hodor"
description = "An exit blocker, can hold the door until a task is completed"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
ctrlc = "3.4.5"
log = { workspace = true }
