[package]
name = "brk_state"
description = "Various states used mainly by the computer"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
brk_core = { workspace = true }
derive_deref = { workspace = true }
serde = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["zerocopy"]
