[package]
name = "brk_exit"
description = "An exit blocker built on top of ctrlc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ctrlc = "3.4.5"
log = { workspace = true }
