[package]
name = "bomputer"
version = "0.1.0"
edition = "2021"

[dependencies]
bindex = { path = "../bindex" }
color-eyre = "0.6.3"
derive_deref = "1.1.1"
exit = { path = "../exit" }
jiff = "0.1.27"
rayon = "1.10.0"
