[package]
name = "storable_vec"
description = "A very small, fast, efficient and simple storable Vec"
version = "0.1.2"
license = "MIT"
keywords = ["vec", "disk", "data"]
categories = ["database"]
edition = "2021"

[dependencies]
memmap2 = "0.9.5"
unsafe_slice_serde = { workspace = true }
