[package]
name = "bindex"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
biter = { workspace = true }
color-eyre = { workspace = true }
derive_deref = { workspace = true }
exit = { workspace = true }
fjall = { workspace = true }
jiff = { workspace = true }
rapidhash = "1.3.0"
rayon = { workspace = true }
# snkrj = { workspace = true }
storable_vec = { workspace = true }
unsafe_slice_serde = { workspace = true }
