[package]
name = "brk_printer"
description = "A clean logger"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
color-eyre = { workspace = true }
env_logger = "0.11.6"
jiff = { workspace = true }
log = { workspace = true }
