[package]
name = "bindex"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin_hashes = "0.16.0"
biter = "0.2.2"
color-eyre = "0.6.3"
ctrlc = "3.4.5"
derive_deref = "1.1.1"
memmap2 = "0.9.5"
rayon = "1.10.0"
snkrj = { path = "../snkrj" }
canopydb = { git = "https://github.com/arthurprs/canopydb" }
