use num_enum::{FromPrimitive, IntoPrimitive};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use strum::Display;
use vecdb::{Bytes, Formattable};

// Slug of a mining pool
#[allow(clippy::upper_case_acronyms)]
#[derive(
    Default,
    Debug,
    Copy,
    Display,
    Clone,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Serialize,
    Deserialize,
    JsonSchema,
    FromPrimitive,
    IntoPrimitive,
)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
#[repr(u8)]
pub enum PoolSlug {
    #[default]
    Unknown,
    BlockFills,
    UltimusPool,
    TerraPool,
    Luxor,
    OneThash,
    BtcCom,
    Bitfarms,
    HuobiPool,
    WayiCn,
    CanoePool,
    BtcTop,
    BitcoinCom,
    Pool175btc,
    GbMiners,
    AXbt,
    AsicMiner,
    BitMinter,
    BitcoinRussia,
    BtcServ,
    SimplecoinUs,
    BtcGuild,
    Eligius,
    OzCoin,
    EclipseMc,
    MaxBtc,
    TripleMining,
    CoinLab,
    Pool50btc,
    GhashIo,
    StMiningCorp,
    Bitparking,
    Mmpool,
    Polmine,
    KncMiner,
    Bitalo,
    F2Pool,
    Hhtt,
    MegaBigPower,
    MtRed,
    NmcBit,
    YourbtcNet,
    GiveMeCoins,
    BraiinsPool,
    AntPool,
    MultiCoinCo,
    BcpoolIo,
    Cointerra,
    KanoPool,
    SoloCk,
    CkPool,
    NiceHash,
    BitClub,
    BitcoinAffiliateNetwork,
    Btcc,
    BwPool,
    ExxBw,
    Bitsolo,
    BitFury,
    TwentyOneInc,
    DigitalBtc,
    EightBaochi,
    MyBtcCoinPool,
    TbDice,
    HashPool,
    Nexious,
    BravoMining,
    HotPool,
    OkExPool,
    BcMonster,
    OneHash,
    Bixin,
    TatmasPool,
    ViaBtc,
    ConnectBtc,
    BatPool,
    Waterhole,
    DcExploration,
    Dcex,
    BtPool,
    FiftyEightCoin,
    BitcoinIndia,
    ShawnP0wers,
    PHashIo,
    RigPool,
    HaoZhuZhu,
    SevenPool,
    MiningKings,
    HashBx,
    DPool,
    Rawpool,
    Haominer,
    Helix,
    BitcoinUkraine,
    Poolin,
    SecretSuperstar,
    TigerpoolNet,
    SigmapoolCom,
    OkpoolTop,
    Hummerpool,
    Tangpool,
    BytePool,
    SpiderPool,
    NovaBlock,
    MiningCity,
    BinancePool,
    Minerium,
    LubianCom,
    Okkong,
    AaoPool,
    EmcdPool,
    FoundryUsa,
    SbiCrypto,
    ArkPool,
    PureBtcCom,
    MaraPool,
    KuCoinPool,
    EntrustCharityPool,
    OkMiner,
    Titan,
    PegaPool,
    BtcNuggets,
    CloudHashing,
    DigitalXMintsy,
    Telco214,
    BtcPoolParty,
    Multipool,
    TransactionCoinMining,
    BtcDig,
    TrickysBtcPool,
    BtcMp,
    Eobot,
    Unomp,
    Patels,
    GoGreenLight,
    EkanemBtc,
    Canoe,
    Tiger,
    OneM1x,
    Zulupool,
    SecPool,
    Ocean,
    WhitePool,
    Wk057,
    FutureBitApolloSolo,
    CarbonNegative,
    PortlandHodl,
    Phoenix,
    Neopool,
    MaxiPool,
    BitFuFuPool,
    LuckyPool,
    MiningDutch,
    PublicPool,
    MiningSquared,
    InnopolisTech,
    BtcLab,
    Parasite,
    #[schemars(skip)]
    Dummy158,
    #[schemars(skip)]
    Dummy159,
    #[schemars(skip)]
    Dummy160,
    #[schemars(skip)]
    Dummy161,
    #[schemars(skip)]
    Dummy162,
    #[schemars(skip)]
    Dummy163,
    #[schemars(skip)]
    Dummy164,
    #[schemars(skip)]
    Dummy165,
    #[schemars(skip)]
    Dummy166,
    #[schemars(skip)]
    Dummy167,
    #[schemars(skip)]
    Dummy168,
    #[schemars(skip)]
    Dummy169,
    #[schemars(skip)]
    Dummy170,
    #[schemars(skip)]
    Dummy171,
    #[schemars(skip)]
    Dummy172,
    #[schemars(skip)]
    Dummy173,
    #[schemars(skip)]
    Dummy174,
    #[schemars(skip)]
    Dummy175,
    #[schemars(skip)]
    Dummy176,
    #[schemars(skip)]
    Dummy177,
    #[schemars(skip)]
    Dummy178,
    #[schemars(skip)]
    Dummy179,
    #[schemars(skip)]
    Dummy180,
    #[schemars(skip)]
    Dummy181,
    #[schemars(skip)]
    Dummy182,
    #[schemars(skip)]
    Dummy183,
    #[schemars(skip)]
    Dummy184,
    #[schemars(skip)]
    Dummy185,
    #[schemars(skip)]
    Dummy186,
    #[schemars(skip)]
    Dummy187,
    #[schemars(skip)]
    Dummy188,
    #[schemars(skip)]
    Dummy189,
    #[schemars(skip)]
    Dummy190,
    #[schemars(skip)]
    Dummy191,
    #[schemars(skip)]
    Dummy192,
    #[schemars(skip)]
    Dummy193,
    #[schemars(skip)]
    Dummy194,
    #[schemars(skip)]
    Dummy195,
    #[schemars(skip)]
    Dummy196,
    #[schemars(skip)]
    Dummy197,
    #[schemars(skip)]
    Dummy198,
    #[schemars(skip)]
    Dummy199,
    #[schemars(skip)]
    Dummy200,
    #[schemars(skip)]
    Dummy201,
    #[schemars(skip)]
    Dummy202,
    #[schemars(skip)]
    Dummy203,
    #[schemars(skip)]
    Dummy204,
    #[schemars(skip)]
    Dummy205,
    #[schemars(skip)]
    Dummy206,
    #[schemars(skip)]
    Dummy207,
    #[schemars(skip)]
    Dummy208,
    #[schemars(skip)]
    Dummy209,
    #[schemars(skip)]
    Dummy210,
    #[schemars(skip)]
    Dummy211,
    #[schemars(skip)]
    Dummy212,
    #[schemars(skip)]
    Dummy213,
    #[schemars(skip)]
    Dummy214,
    #[schemars(skip)]
    Dummy215,
    #[schemars(skip)]
    Dummy216,
    #[schemars(skip)]
    Dummy217,
    #[schemars(skip)]
    Dummy218,
    #[schemars(skip)]
    Dummy219,
    #[schemars(skip)]
    Dummy220,
    #[schemars(skip)]
    Dummy221,
    #[schemars(skip)]
    Dummy222,
    #[schemars(skip)]
    Dummy223,
    #[schemars(skip)]
    Dummy224,
    #[schemars(skip)]
    Dummy225,
    #[schemars(skip)]
    Dummy226,
    #[schemars(skip)]
    Dummy227,
    #[schemars(skip)]
    Dummy228,
    #[schemars(skip)]
    Dummy229,
    #[schemars(skip)]
    Dummy230,
    #[schemars(skip)]
    Dummy231,
    #[schemars(skip)]
    Dummy232,
    #[schemars(skip)]
    Dummy233,
    #[schemars(skip)]
    Dummy234,
    #[schemars(skip)]
    Dummy235,
    #[schemars(skip)]
    Dummy236,
    #[schemars(skip)]
    Dummy237,
    #[schemars(skip)]
    Dummy238,
    #[schemars(skip)]
    Dummy239,
    #[schemars(skip)]
    Dummy240,
    #[schemars(skip)]
    Dummy241,
    #[schemars(skip)]
    Dummy242,
    #[schemars(skip)]
    Dummy243,
    #[schemars(skip)]
    Dummy244,
    #[schemars(skip)]
    Dummy245,
    #[schemars(skip)]
    Dummy246,
    #[schemars(skip)]
    Dummy247,
    #[schemars(skip)]
    Dummy248,
    #[schemars(skip)]
    Dummy249,
    #[schemars(skip)]
    Dummy250,
    #[schemars(skip)]
    Dummy251,
    #[schemars(skip)]
    Dummy252,
    #[schemars(skip)]
    Dummy253,
    #[schemars(skip)]
    Dummy254,
    #[schemars(skip)]
    Dummy255,
}

impl Formattable for PoolSlug {
    #[inline(always)]
    fn may_need_escaping() -> bool {
        false
    }
}

impl Bytes for PoolSlug {
    type Array = [u8; size_of::<Self>()];

    #[inline]
    fn to_bytes(&self) -> Self::Array {
        [*self as u8]
    }

    #[inline]
    fn from_bytes(bytes: &[u8]) -> vecdb::Result<Self> {
        if bytes.len() != size_of::<Self>() {
            return Err(vecdb::Error::WrongLength {
                expected: size_of::<Self>(),
                received: bytes.len(),
            });
        };
        // SAFETY: PoolId is repr(u8) and we're transmuting from u8
        // All values 0-255 are valid (includes dummy variants)
        let s: Self = unsafe { std::mem::transmute(bytes[0]) };
        Ok(s)
    }
}
