[package]
name = "hodor"
description = "Hold the door, an exit blocker built on top of ctrlc"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ctrlc = "3.4.5"
log = { workspace = true }
